### PR TITLE
Lamaliang patch 3 for add T2MAX and T2MIN

### PR DESCRIPTION
**Pull request by lamaliang**
add two variables for t2max and t2min

### CODE REVIEW

**Comment by bentian** [comment]
@lamaliang Can you revise your commit base on revise commit (https://github.com/bentian/corrdiff_input/commit/592f1bb161ec6374f7e30f6493c0f1cd0d885347) ? 

Base on your commits I renamed the channel lists to improve readability. If you don't want to spend time I can merge the revised commit directly, with message saying it's based on your commit.

Let me know.

**Comment by bentian** [comment]
I'll go directly merge the revised commit. Thanks for this PR! 

> @lamaliang Can you revise your commit base on revise commit (https://github.com/bentian/corrdiff_input/commit/592f1bb161ec6374f7e30f6493c0f1cd0d885347) ?

**Comment by bentian** [comment]
Close as #3 merged.

**Comment by lamaliang** [comment]
@bentian Thank you for merging the file. As this is my first time creating a pull request, I appreciate your guidance and will follow your suggestions. Thank you!

**Pull request closed without merging**
